### ISSUE TITLE
IOU not working

### ISSUE THREAD

**Issue by freeshare2011** [jsimonetti/docker-gns3-server#100]
Hello,

The docker-gns3-server is very nice, want to explore the possibility to add IOU support.

I use IOS on GNS3-VM or docker without issue, only IOU on docker doesn't work, some of the command to check the file or environment from both as below

on GNS3 VM
Use file command to check the IOU file type
/opt/gns3/images/IOU$ file i86bi-linux-l2-adventerprise-15.1b.bin
i86bi-linux-l2-adventerprise-15.1b.bin: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.2, for GNU/Linux 2.2.5, stripped

use ldd command to check the required share library
/opt/gns3/images/IOU$ ldd i86bi-linux-l2-adventerprise-15.1b.bin
        linux-gate.so.1 (0xf7fc0000)
        libcrypto.so.4 => /lib/i386-linux-gnu/libcrypto.so.4 (0xf7cf6000)
        libpthread.so.0 => /lib/i386-linux-gnu/libpthread.so.0 (0xf7cd3000)
        libm.so.6 => /lib/i386-linux-gnu/libm.so.6 (0xf7bce000)
        libgcc_s.so.1 => /lib/i386-linux-gnu/libgcc_s.so.1 (0xf7baf000)
        libc.so.6 => /lib/i386-linux-gnu/libc.so.6 (0xf79c0000)
        libdl.so.2 => /lib/i386-linux-gnu/libdl.so.2 (0xf79ba000)
        /lib/ld-linux.so.2 (0xf7fc2000)

Use ls command to check the shared library for i386 arch, all the required library are there.
/lib/i386-linux-gnu$ ls
audit                    libgpg-error.so.0       libpthread.so.0
engines-1.1              libgpg-error.so.0.28.0  libreadline.so.8
gconv                    libhistory.so.8         libreadline.so.8.0
ld-2.31.so               libhistory.so.8.0       libresolv-2.31.so
ld-linux.so.2            libidn2.so.0            libresolv.so.2
libanl-2.31.so           libidn2.so.0.3.6        librt-2.31.so
libanl.so.1              libm-2.31.so            librt.so.1
libassuan.so.0           libmemusage.so          libSegFault.so
libassuan.so.0.8.3       libm.so.6               libsqlite3.so.0
libBrokenLocale-2.31.so  libnsl-2.31.so          libsqlite3.so.0.8.6
libBrokenLocale.so.1     libnsl.so.1             libssl.so.1.1
libbz2.so.1              libnss_compat-2.31.so   libthread_db-1.0.so
libbz2.so.1.0            libnss_compat.so.2      libthread_db.so.1
libbz2.so.1.0.4          libnss_dns-2.31.so      libtic.so.6
libc-2.31.so             libnss_dns.so.2         libtic.so.6.2
libcrypto.so.1.1         libnss_files-2.31.so    libtinfo.so.6
libcrypto.so.4           libnss_files.so.2       libtinfo.so.6.2
libcrypt.so.1            libnss_hesiod-2.31.so   libunistring.so.2
libcrypt.so.1.1.0        libnss_hesiod.so.2      libunistring.so.2.1.0
libc.so.6                libnss_nis-2.31.so      libutil-2.31.so
libdl-2.31.so            libnss_nisplus-2.31.so  libutil.so.1
libdl.so.2               libnss_nisplus.so.2     libz.so.1
libgcc_s.so.1            libnss_nis.so.2         libz.so.1.2.11
libgcrypt.so.20          libpcprofile.so
libgcrypt.so.20.2.5      libpthread-2.31.so

on docker-gns3-server
when start IOU, it said Invalid IOU license key detected in iourc file /data/.iourc
the command (same as gns3-VM) output as below:
file command
/home/azureuser/gns3/images/IOU# file i86bi-linux-l3-adventerprisek9-15.4.1T.bin
i86bi-linux-l3-adventerprisek9-15.4.1T.bin: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.2, for GNU/Linux 2.2.5, stripped
comments: it’s the same as GNS3-VM

ldd command
/home/azureuser/gns3/images/IOU# ldd i86bi-linux-l3-adventerprisek9-15.4.1T.bin
        not a dynamic executable
comments: it seems lack of necessary i386 arch shared library

use find command didn’t found the i386 shared libraries.

I’m thinking if the docker missing the i386 shared library which can be further update the docker or it’s intend not to supportIOU at all.

The intention is have the gns3 server running on azure cloud, so I can access the test environment anywhere and anytime.

not sure this should be a feature request or issue. thanks a lot.

**Comment by talondnb** [comment]
I've just hit this myself. Hoping we can have a solution soon.

**Comment by talondnb** [comment]
https://github.com/GNS3/gns3-vm/blob/focal-stable/config/install.sh#L61-L62

I've found the above in the gns3-vm package - excuse my lack of knowledge but would this be relevant in getting IOU working in this package?

**Comment by jsimonetti** [comment]
Hi,
I have not found the time to look into this. My major problem being that I cannot test this myself as I don't own a license.
It should be fairly straightforward to add i386 support for Alpine Linux (which is the base for this container), but without knowing exactly which packages require installation, this is pure speculation from my part.
The best would be to find the source for the IOU package used by GNS themselves, as that should in theory contain the required dependencies.
I'll see if I can do some digging later this week.

**Comment by talondnb** [comment]
I can send over a few files if you want, to help you get this working?

**Comment by jsimonetti** [comment]
So, I had a quick glance at it and it turns out Alpine Linux does not support multiarch. This means the container needs to be either x86 of x86_64. It cannot run both at the same time.
This is unfortunate.

To support IOU, it seems like this container needs to be completely rebuild. Since I have no use for IOU personally, I have no intention to do this. Sorry.

Feel free to fork this project and switch it to i386. I am happy to help out if needed. However, I will not be maintaining one myself.
