### ISSUE TITLE
KVM missing?

### ISSUE THREAD

**Issue by Azertooth** [jsimonetti/docker-gns3-server#14]
I'm trying to start an appliance on the gn3-server but it returns me this error

`KVM acceleration cannot be used (/dev/kvm doesn't exist). It is possible to turn off KVM support in the gns3_server.conf by adding enable_kvm = false to the [Qemu] section.`

**Comment by Azertooth** [comment]
solved: container was missing --privileged argument

**Comment by jsimonetti** [comment]
Good to hear you fixed this yourself!
I have unfortunately not found a way yet to run the container unprivileged.
