### ISSUE TITLE
busybox missing in gns3 server version 2.2.46

### ISSUE THREAD

**Issue by minpeter** [jsimonetti/docker-gns3-server#145]
I know it's not a problem with this repo.

However, I opened an issue because it can be resolved simply by updating the dockerfile until the next version is released.

```dockerfile
FROM alpine:3.19.1

# Install the magic wrapper.
ADD ./start.sh /start.sh
ADD ./config.ini /config.ini
ADD ./requirements.txt /requirements.txt
COPY dependencies.json /tmp/dependencies.json

RUN mkdir /data && \
    apk add --no-cache --virtual=build-dependencies jq gcc python3-dev musl-dev linux-headers \
    && jq -r 'to_entries | .[] | .key + "=" + .value' /tmp/dependencies.json | xargs apk add --no-cache \
    && pip install -r /requirements.txt --break-system-packages \
    && apk del --purge build-dependencies

CMD [ "/start.sh" ]

# this new line!!
RUN ln -s /bin/busybox /usr/lib/python3.11/site-packages/gns3server/compute/docker/resources/bin
WORKDIR /data

VOLUME ["/data"]
```

This temporarily resolves the issue of Docker not running.

**Comment by jsimonetti** [comment]
Hi, thank you for submitting this.
Is this a know issue that is being worked on somewhere? If so, could you link to it from here so we can track when it is fixed?

**Comment by jsimonetti** [comment]
@minpeter can you confirm the last docker image fixes your problem?

**Comment by minpeter** [comment]
Solved. thanks :)

**Comment by jsimonetti** [comment]
Ill keep this open until we get an update from upstream

**Comment by minpeter** [comment]
Upstream issue is closed.
They decided to no longer include busybox in their packaging.

I think we can review whether the busybox connection implemented above is the best practice and close this issue.

**Comment by jsimonetti** [comment]
I have added a permanent solution for this.

Please re-open if this did not fix your issue.
