### ISSUE TITLE
Python error

### ISSUE THREAD

**Issue by milenBG** [jsimonetti/docker-gns3-server#2]
Dear Jeroen Simonetti,

I used successfully a pervious image "sha256: 4fd4df58677926fa38c414aab9e2af8a9c5752b242493c8b305041876ebc3ac7", but after updating to the latest, it fails with some python error. This is the log:

time="2020-01-14T09:43:08.702152895Z" level=info msg="Starting up"
time="2020-01-14T09:43:08.708141805Z" level=info msg="libcontainerd: started new containerd process" pid=25
time="2020-01-14T09:43:08.708219330Z" level=info msg="parsed scheme: \"unix\"" module=grpc
time="2020-01-14T09:43:08.708251946Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
time="2020-01-14T09:43:08.708289870Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///var/run/docker/containerd/containerd.sock 0  <nil>}] <nil>}" module=grpc
time="2020-01-14T09:43:08.708353497Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
time="2020-01-14T09:43:08.752598537Z" level=info msg="starting containerd" revision=ff48f57fc83a8c44cf4ad5d672424a98ba37ded6 version=v1.3.2
time="2020-01-14T09:43:08.786628369Z" level=info msg="loading plugin \"io.containerd.content.v1.content\"..." type=io.containerd.content.v1
time="2020-01-14T09:43:08.786716161Z" level=info msg="loading plugin \"io.containerd.snapshotter.v1.btrfs\"..." type=io.containerd.snapshotter.v1
time="2020-01-14T09:43:08.787057271Z" level=info msg="skip loading plugin \"io.containerd.snapshotter.v1.btrfs\"..." error="path /data/docker/containerd/daemon/io.containerd.snapshotter.v1.btrfs must be a btrfs filesystem to be used with the btrfs snapshotter: skip plugin" type=io.containerd.snapshotter.v1
time="2020-01-14T09:43:08.787098618Z" level=info msg="loading plugin \"io.containerd.snapshotter.v1.devmapper\"..." type=io.containerd.snapshotter.v1
time="2020-01-14T09:43:08.787141012Z" level=warning msg="failed to load plugin io.containerd.snapshotter.v1.devmapper" error="devmapper not configured"
time="2020-01-14T09:43:08.787167342Z" level=info msg="loading plugin \"io.containerd.snapshotter.v1.aufs\"..." type=io.containerd.snapshotter.v1
time="2020-01-14T09:43:08.787883925Z" level=info msg="skip loading plugin \"io.containerd.snapshotter.v1.aufs\"..." error="modprobe aufs failed: \"modprobe: can't change directory to '/lib/modules': No such file or directory\\n\": exit status 1: skip plugin" type=io.containerd.snapshotter.v1
time="2020-01-14T09:43:08.787918916Z" level=info msg="loading plugin \"io.containerd.snapshotter.v1.native\"..." type=io.containerd.snapshotter.v1
time="2020-01-14T09:43:08.787970040Z" level=info msg="loading plugin \"io.containerd.snapshotter.v1.overlayfs\"..." type=io.containerd.snapshotter.v1
time="2020-01-14T09:43:08.788119782Z" level=info msg="loading plugin \"io.containerd.snapshotter.v1.zfs\"..." type=io.containerd.snapshotter.v1
time="2020-01-14T09:43:08.788362205Z" level=info msg="skip loading plugin \"io.containerd.snapshotter.v1.zfs\"..." error="path /data/docker/containerd/daemon/io.containerd.snapshotter.v1.zfs must be a zfs filesystem to be used with the zfs snapshotter: skip plugin" type=io.containerd.snapshotter.v1
time="2020-01-14T09:43:08.788392377Z" level=info msg="loading plugin \"io.containerd.metadata.v1.bolt\"..." type=io.containerd.metadata.v1
time="2020-01-14T09:43:08.788432117Z" level=warning msg="could not use snapshotter devmapper in metadata plugin" error="devmapper not configured"
time="2020-01-14T09:43:08.788453140Z" level=info msg="metadata content store policy set" policy=shared
time="2020-01-14T09:43:08.788606863Z" level=info msg="loading plugin \"io.containerd.differ.v1.walking\"..." type=io.containerd.differ.v1
time="2020-01-14T09:43:08.788636545Z" level=info msg="loading plugin \"io.containerd.gc.v1.scheduler\"..." type=io.containerd.gc.v1
time="2020-01-14T09:43:08.788690953Z" level=info msg="loading plugin \"io.containerd.service.v1.containers-service\"..." type=io.containerd.service.v1
time="2020-01-14T09:43:08.788717702Z" level=info msg="loading plugin \"io.containerd.service.v1.content-service\"..." type=io.containerd.service.v1
time="2020-01-14T09:43:08.788753741Z" level=info msg="loading plugin \"io.containerd.service.v1.diff-service\"..." type=io.containerd.service.v1
time="2020-01-14T09:43:08.788778884Z" level=info msg="loading plugin \"io.containerd.service.v1.images-service\"..." type=io.containerd.service.v1
time="2020-01-14T09:43:08.788802211Z" level=info msg="loading plugin \"io.containerd.service.v1.leases-service\"..." type=io.containerd.service.v1
time="2020-01-14T09:43:08.788839507Z" level=info msg="loading plugin \"io.containerd.service.v1.namespaces-service\"..." type=io.containerd.service.v1
time="2020-01-14T09:43:08.788862276Z" level=info msg="loading plugin \"io.containerd.service.v1.snapshots-service\"..." type=io.containerd.service.v1
time="2020-01-14T09:43:08.788897616Z" level=info msg="loading plugin \"io.containerd.runtime.v1.linux\"..." type=io.containerd.runtime.v1
time="2020-01-14T09:43:08.789086889Z" level=info msg="loading plugin \"io.containerd.runtime.v2.task\"..." type=io.containerd.runtime.v2
time="2020-01-14T09:43:08.789248155Z" level=info msg="loading plugin \"io.containerd.monitor.v1.cgroups\"..." type=io.containerd.monitor.v1
time="2020-01-14T09:43:08.789761566Z" level=info msg="loading plugin \"io.containerd.service.v1.tasks-service\"..." type=io.containerd.service.v1
time="2020-01-14T09:43:08.789800887Z" level=info msg="loading plugin \"io.containerd.internal.v1.restart\"..." type=io.containerd.internal.v1
time="2020-01-14T09:43:08.789867586Z" level=info msg="loading plugin \"io.containerd.grpc.v1.containers\"..." type=io.containerd.grpc.v1
time="2020-01-14T09:43:08.789920038Z" level=info msg="loading plugin \"io.containerd.grpc.v1.content\"..." type=io.containerd.grpc.v1
time="2020-01-14T09:43:08.789943156Z" level=info msg="loading plugin \"io.containerd.grpc.v1.diff\"..." type=io.containerd.grpc.v1
time="2020-01-14T09:43:08.789965435Z" level=info msg="loading plugin \"io.containerd.grpc.v1.events\"..." type=io.containerd.grpc.v1
time="2020-01-14T09:43:08.790002591Z" level=info msg="loading plugin \"io.containerd.grpc.v1.healthcheck\"..." type=io.containerd.grpc.v1
time="2020-01-14T09:43:08.790026547Z" level=info msg="loading plugin \"io.containerd.grpc.v1.images\"..." type=io.containerd.grpc.v1
time="2020-01-14T09:43:08.790052459Z" level=info msg="loading plugin \"io.containerd.grpc.v1.leases\"..." type=io.containerd.grpc.v1
time="2020-01-14T09:43:08.790089755Z" level=info msg="loading plugin \"io.containerd.grpc.v1.namespaces\"..." type=io.containerd.grpc.v1
time="2020-01-14T09:43:08.790112174Z" level=info msg="loading plugin \"io.containerd.internal.v1.opt\"..." type=io.containerd.internal.v1
time="2020-01-14T09:43:08.790351454Z" level=info msg="loading plugin \"io.containerd.grpc.v1.snapshots\"..." type=io.containerd.grpc.v1
time="2020-01-14T09:43:08.790382743Z" level=info msg="loading plugin \"io.containerd.grpc.v1.tasks\"..." type=io.containerd.grpc.v1
time="2020-01-14T09:43:08.790423531Z" level=info msg="loading plugin \"io.containerd.grpc.v1.version\"..." type=io.containerd.grpc.v1
time="2020-01-14T09:43:08.790446439Z" level=info msg="loading plugin \"io.containerd.grpc.v1.introspection\"..." type=io.containerd.grpc.v1
time="2020-01-14T09:43:08.790798584Z" level=info msg=serving... address=/var/run/docker/containerd/containerd-debug.sock
time="2020-01-14T09:43:08.790904605Z" level=info msg=serving... address=/var/run/docker/containerd/containerd.sock.ttrpc
time="2020-01-14T09:43:08.791015794Z" level=info msg=serving... address=/var/run/docker/containerd/containerd.sock
time="2020-01-14T09:43:08.791060982Z" level=info msg="containerd successfully booted in 0.039500s"
time="2020-01-14T09:43:08.804270889Z" level=info msg="parsed scheme: \"unix\"" module=grpc
time="2020-01-14T09:43:08.804300781Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
time="2020-01-14T09:43:08.804337239Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///var/run/docker/containerd/containerd.sock 0  <nil>}] <nil>}" module=grpc
time="2020-01-14T09:43:08.804455831Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
time="2020-01-14T09:43:08.805305952Z" level=info msg="parsed scheme: \"unix\"" module=grpc
time="2020-01-14T09:43:08.805340873Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
time="2020-01-14T09:43:08.805397306Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///var/run/docker/containerd/containerd.sock 0  <nil>}] <nil>}" module=grpc
time="2020-01-14T09:43:08.805432157Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
time="2020-01-14T09:43:08.877631935Z" level=warning msg="Your kernel does not support cgroup rt period"
time="2020-01-14T09:43:08.877662596Z" level=warning msg="Your kernel does not support cgroup rt runtime"
time="2020-01-14T09:43:08.877674609Z" level=warning msg="Your kernel does not support cgroup blkio weight"
time="2020-01-14T09:43:08.877686621Z" level=warning msg="Your kernel does not support cgroup blkio weight_device"
time="2020-01-14T09:43:08.877952441Z" level=info msg="Loading containers: start."
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (yarl 1.4.2 (/usr/lib/python3.8/site-packages), Requirement.parse('yarl==1.3.0'), {'gns3-server'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/gns3server", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3252, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'yarl==1.3.0' distribution was not found and is required by gns3-server

Do I make some mistake or miss something?
Thanks in advance!

Best Regards,

**Comment by jsimonetti** [comment]
This looks like i missed a python requirement for the later versions of gns3server.
Ill have a look.

**Comment by jsimonetti** [comment]
I disabled the testing repo of alpine. This was never really needed and seems to have pulled in some incompatible python versions.

latest / sha256:1fc637ed63a163c7257b73cea9743bb52307dbdbc8d7079e66a7cb927c803403 fixes this.
