### ISSUE TITLE
2.2.25 update

### ISSUE THREAD

**Issue by hasbean** [jsimonetti/docker-gns3-server#27]
Hello,

2.2.25 client is out but sadly I can't use it since the gns3-server image on Docker Hub is 2.2.22

Help?
Thanks!

**Comment by jsimonetti** [comment]
Unfortunately docker hub has stopped autobuilds for non-paying accounts.
This means the hub version no longer follows this repository.
If you want the latest version, you can build from this repository manually.

**Comment by jsimonetti** [comment]
FYI, I added a github action that will now build and push the image to docker hub. It should now be updated automatically action.
Please try either the `latest` or `2.2.25` image tag.
