### ISSUE TITLE
Update to 2.2.17

### ISSUE THREAD

**Issue by thomasvvugt** [jsimonetti/docker-gns3-server#5]
Connecting to a docker container running the latest image will return the following error;
`Client version 2.2.17 is not the same as server (controller) version 2.2.15`

Could you please update the server version to 2.2.17? Thank you!

**Comment by jsimonetti** [comment]
I triggered a new build. It should be up2date in a few minutes on docker hub.
Closingnow, but if you have any questions feel free to reopen.

**Comment by thomasvvugt** [comment]
Thanks @jsimonetti,
I have pulled the new image and restarted the server, but I am getting the following error message;

![image](https://user-images.githubusercontent.com/56607882/101243753-99849f80-3702-11eb-8d8d-f5d1a4747079.png)

Could you check whether the new image is working correctly for you?
Thanks!

**Comment by thomasvvugt** [comment]
It seems that the controller (server) version is still at 2.2.16 in the new build

**Comment by jsimonetti** [comment]
The server is build using packages from Alpine linux edge. It looks like version 2.2.17 only came out yesterday. I have spun up a new build and that should be on 2.2.17.
Sorry for the misinformation.

**Comment by thomasvvugt** [comment]
Hi @jsimonetti, thanks very much. The image seems to have the latest version right now. Stay awesome! 😁
