### ISSUE TITLE
Pass in config file on container creation

### ISSUE THREAD

**Issue by k4kfh** [jsimonetti/docker-gns3-server#6]
Hello, I'm relatively new to Docker so forgive me if this is a dumb question. I'd like to be able to configure username and password when I create the container. I've got an automated setup that will be creating these containers so I'd like to do it from the Docker API rather than having to manually enter the container and edit the config. Is this possible?

Thank you so much for this project, btw! It's been a huge help.

**Comment by jsimonetti** [comment]
Hi @k4kfh ,
Normally you would use environment variables and a startup script to set those things for you during startup.
Have a look at https://github.com/jsimonetti/docker-gns3-server/blob/master/start.sh to see how I provide variables to change the configuration such as CONFIG or BRIDGE_ADDRESS.
